# Generated by Django 3.2.20 on 2024-02-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active_sessions',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('acc', models.TextField()),
                ('profile', models.TextField()),
                ('startDate', models.TextField(db_column='start date')),
                ('startTime', models.TextField(db_column='start time')),
                ('endDate', models.TextField(db_column='end date')),
                ('endTime', models.TextField(db_column='end time')),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('acc', models.TextField()),
                ('code', models.TextField()),
                ('amount', models.IntegerField()),
                ('source', models.TextField()),
                ('date', models.TextField()),
                ('time', models.TextField()),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('acc', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('package', models.IntegerField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('install_date', models.TextField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
