# Generated by Django 3.2.20 on 2024-02-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Active_sessions',
            new_name='Sessions',
        ),
    ]
