# Generated by Django 3.2.20 on 2024-02-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_rename_active_sessions_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('acc', models.TextField()),
                ('moneyIn', models.IntegerField(db_column='money in')),
                ('moneyOut', models.IntegerField(db_column='money out')),
                ('description', models.TextField()),
                ('date', models.TextField()),
            ],
            options={
                'db_table': 'finances',
            },
        ),
    ]
