# Generated by Django 3.2.20 on 2024-02-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_finances'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pkgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pno', models.IntegerField()),
                ('name', models.TextField()),
                ('speed', models.IntegerField()),
                ('days', models.IntegerField()),
                ('max_users', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pkg_type', models.TextField(db_column='type')),
            ],
            options={
                'db_table': 'package',
            },
        ),
    ]
