# Generated by Django 3.2.20 on 2024-02-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_pkgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkgs',
            name='pno',
            field=models.IntegerField(db_column='pno'),
        ),
    ]
