# Generated by Django 3.2.20 on 2024-02-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_pkgs_pno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pkgs',
            name='id',
        ),
        migrations.AlterField(
            model_name='pkgs',
            name='pno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
