# Generated by Django 3.2.20 on 2024-02-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_auto_20240225_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.TextField()),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='finances',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pkgs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sessions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
