# Generated by Django 5.0.2 on 2024-02-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('acc', models.TextField()),
                ('code', models.TextField()),
                ('amount', models.IntegerField()),
                ('source', models.TextField()),
                ('date', models.TextField()),
                ('time', models.TextField()),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
