# Generated by Django 5.0.2 on 2024-02-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active_sessions',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('acc', models.TextField()),
                ('profile', models.TextField()),
                ('startDate', models.TextField()),
                ('startTime', models.TextField()),
                ('endDate', models.TextField()),
                ('endTime', models.TextField()),
                ('status', models.TextField()),
                ('creationDate', models.TextField()),
            ],
            options={
                'db_table': 'active',
            },
        ),
    ]
