# Generated by Django 5.0.2 on 2024-02-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_web_app', '0002_active_sessions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='active_sessions',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='active_sessions',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='active_sessions',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='active_sessions',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='active_sessions',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.AlterModelTable(
            name='active_sessions',
            table='sessions',
        ),
    ]
