# Generated by Django 5.0.2 on 2024-02-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web_app', '0003_rename_creationdate_active_sessions_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_sessions',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='active_sessions',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='active_sessions',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='active_sessions',
            name='start_time',
        ),
        migrations.AddField(
            model_name='active_sessions',
            name='endDate',
            field=models.TextField(db_column='end date', default='1-Jan-2024'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='active_sessions',
            name='endTime',
            field=models.TextField(db_column='end time', default='12:00 AMM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='active_sessions',
            name='startDate',
            field=models.TextField(db_column='start date', default='1-Jan-2024'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='active_sessions',
            name='startTime',
            field=models.TextField(db_column='start time', default='12:00 AM'),
            preserve_default=False,
        ),
    ]
